on:
  push:
    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

        with:
          packages: |
            any::tidyverse 
      - name: ⚙️ Install lcov
        run: |
          sudo apt-get install -y pip
          sudo pip install igraph
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install -y libglpk-dev libtk-img libgdal-dev libgda-5.0-4 libproj-dev libudunits2-dev tcl tk tcl-dev tk-dev
          sudo apt-get install -y libglu1
          sudo apt-get install -y openjdk-11-jdk
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install packages
        run: |
          Rscript -e "install.packages(c('devtools','rgl','glmnet','gam','fastAdaboost','doParallel','adabag','plotrix','Formula','plotmo','TeachingDemos','earth','mda','rprojroot','diffobj','rematch2','brio','callr','desc','pkgload','praise','processx','ps','waldo','testthat','minqa','nloptr','lme4','abind','coda','ada','mvtnorm','stabs','nnls','quadprog','import','libcoin','inum','partykit','mboost','bitops','caTools','rJava','RWekajars','RWeka','party','coin','strucchange','multcomp','sandwich','modeltools','matrixStats','TH.data','kerndwd','xgboost','RSpectra','rARPACK','HDclassif','kknn','klaR','questionr','labelled','styler','haven','R.cache','readr','R.utils','vroom','R.oo','bit64','combinat','rstudioapi','miniUI','forcats','R.methodsS3','clipr','bit','optimx','monmlp','RSNNS','ncvreg','msaenet','naivebayes','pamr','randomForest','pls','dotCall64','gridExtra','backports','statnet.common','maps','SparseM','MatrixModels','permute','carData','network','spam','viridis','broom','vegan','quantreg','sna','fields','pbkrtest','bipartite','car','plsRglm','stepPlr','ordinalNet','RRF','LiblineaR','DEoptimR','pcaPP','robustbase','rrcov','truncnorm','mclust','Rsolnp','robustDA','rotationForest','kohonen','entropy','corpcor','fdrtool','sda','sdwd','lars','elasticnet','sparseLDA','spls','deepnet','gbm','evtree','wsrf','readxl','stringr','ggplot2','dplyr','DT','shinyBS','plyr','pROC','ggpubr','epiR','OptimalCutpoints','ROCR','pls','mda','shinyalert','combinat','rapport','arm','Cubist','C50','kernlab','misc3d','plot3D','prim','supervisedPRIM','munsell'))"
      - name: Create Package
        run: |
            Rscript -e " install.packages(c('epiR'))
            install.packages("udunits2") library(udunits2) library(units)
            library(epiR)
            pkgload::load_all()
            styler::style_pkg()
            usethis::use_mit_license()
            devtools::document()
            devtools::build_manual()
            devtools::build(args = "--compact-vignettes=gs+qpdf")"