on:
  push:
    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

        with:
          packages: |
            any::tidyverse 
      - name: ⚙️ Install lcov
        run: |
          sudo apt-get install -y pip
          sudo pip install igraph
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install -y libglpk-dev libtk-img libgdal-dev libgda-5.0-4 libproj-dev libudunits2-dev tcl tk tcl-dev tk-dev
          sudo apt-get install -y libglu1
          sudo apt-get install -y openjdk-11-jdk
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Create Package
        run: |
            Rscript -e 'source("./R/createpackage.R")'